add_xpadding: false
bias_datafile: /home/basti/data/hdd/cnn_testbench/resnet18_ssd/extract/wgt_dump/feature_extractor.feature_extractor.0_bias.npy
bias_dw_datafile: null
bias_mean: 0.0
bias_pw_datafile: null
bias_stddev: 1.0
conv_actfunc: relu
conv_dilation: 1
conv_fheight: 7
conv_fwidth: 7
conv_padding: SAME
conv_stride: 2
conv_type: conv
cpp_defs: ''
env_config:
  appdir: /home/basti/data/hdd/test/cnn_asip/core/apps/benchmark_conv2d/runs/ssd_test/resnet18_conv1
  benchmark_root: /home/basti/data/hdd/test/cnn_asip/core/apps/benchmark_conv2d
  projdir: /home/basti/data/hdd/test/cnn_asip/core
  sge_logfile: /home/basti/data/hdd/test/cnn_asip/core/apps/benchmark_conv2d/sge_logs/ssd_test____resnet18_conv1.log
  sge_mail: basti@ice.rwth-aachen.de
ich_cnt: 3
iheight: 300
inp_datafile: /home/basti/data/hdd/cnn_testbench/resnet18_ssd/extract/fmap_dump/feature_extractor.feature_extractor.0_in0.npy
inp_high: 0.0
inp_low: 0.0
input_sparsity: 0.0
intmode: int16
iwidth: 300
och_cnt: 64
ofmap_pad_left: 0
ofmap_pad_right: 0
pool_func: maxpool
pool_ksize: 3
pool_padding: SAME
pool_stride: 2
quant_inp: (5,11,0,TRUNC)
quant_wgt: (5,11,0,TRUNC)
regen_inputs: false
residual_datafile: null
run_name: ssd_test____resnet18_conv1
sim_config:
  clock: 1.9
  density: 0.7
  do_dramsim_power_est: 1
  do_netlist_pwrest: 0
  do_netlistsim: 0
  do_rtl_pwrest: 0
  do_rtlsim: 0
  dramsim_address_mapping_scheme: 4
  dramsim_page_policy: open
  keep_netlist_saif: 0
  keep_rtl_dump: 0
  keep_rtl_saif: 0
  level: layout
  nr_cpus: 1
  rtl_pwrest_dumpstyle: SAIF
  rtl_trace_opcodes: 0
  sge_hosts: belarus|bitbus|claus|druckguss|gonzalus|ionicus|kalyptus|kleinbus|linienbus|quintus|ritus|schampus|tetanus|ryzinus
  sim_model: tmicro_fpga
  sim_prefix: ''
  syn_prefix: ''
  technode: tsmc28
  timing: 1.8
  vlanes: 16
  vsize: 16
tile_tif: 3
tile_tix: 300
tile_tof: 16
valid: true
verify: true
wgt_datafile: /home/basti/data/hdd/cnn_testbench/resnet18_ssd/extract/wgt_dump/feature_extractor.feature_extractor.0_wgts.npy
wgt_dw_datafile: null
wgt_mean: 0.0
wgt_pw_datafile: null
wgt_stddev: 1.0
